### ISSUE TITLE
TypeErrors with latest version - Transaction problems

### ISSUE THREAD

**Issue by unipsycho** [steemit/steem-js#57]
I'm using SteemJS for [autosteem ](https://autosteem.learnthis.ca)and I started getting the following errors with the library recently.  I've checked this with version 0.3.30, 0.4.1 and 0.4.3, they all produce the same error and never used to (at least several weeks ago?). I can reproduce it with just the example steem.html provided as well.
3 out of 4 times, if I run the steem.html, I get the following errors over and over in console:

`Uncaught TypeError: Cannot read property 'transactions' of null
    at api.js:317
    at o (bluebird.js:5236)
    at o.n [as _fulfillmentHandler0] (bluebird.js:2695)
    at o._settlePromise (bluebird.js:3296)
    at o._settlePromise0 (bluebird.js:3344)
    at o._settlePromises (bluebird.js:3423)
    at bluebird.js:175
(anonymous) @ api.js:317
o @ bluebird.js:5236
n @ bluebird.js:2695
o._settlePromise @ bluebird.js:3296
o._settlePromise0 @ bluebird.js:3344
o._settlePromises @ bluebird.js:3423
(anonymous) @ bluebird.js:175
`

If I do nothing, just refresh the browser a bunch of times, eventually 1/4 maybe it will start properly and the broadcast stream will start showing up in the the html.  I rely on this for my autostreem product and so its currently breaking that product online.  Has something changed I'm missing or need to update to resolve this?  Any help would be appreciated, thanks!

**Comment by adcpm** [comment]
Can you try with the version 0.4.4?

**Comment by unipsycho** [comment]
If 0.4.4 is the current dev version, I've done that as well, just redownloaded and tried it again, same results, even with the stream.html example.  Most of time it just errors out, every 1/4(approx) browser refreshes, it starts showing content.  I don't see 0.4.4 in the releases, so assume that is what you meant, still same problem though.

**Comment by adcpm** [comment]
It should be fixed on the last version 0.4.5 can you try again?

**Comment by unipsycho** [comment]
Awesome you guys are able to respond quick on this, I really do appreciate it!  I've redownloaded everything, tried it again.  Unfortunately, same problem is occuring.  I see the edit that was made, makes sense if checking for null, but that is not solving the problem.  Still getting same errors on most browser loads.  I redownloaded, refreshed my cache and tried it from different folders and different browsers to make sure not a cached library or anything as well.  But no luck.

![image](https://cloud.githubusercontent.com/assets/12666072/22496796/0b943d2a-e80a-11e6-8fcb-090c47636dac.png)

**Comment by unipsycho** [comment]
It must be the result that is null, not the transaction.  As in:
![image](https://cloud.githubusercontent.com/assets/12666072/22496867/97e99342-e80a-11e6-8159-3c69ed65d924.png)

**Comment by adcpm** [comment]
I've made a change on that please try again

**Comment by unipsycho** [comment]
OK,just tried the latest. This is eliminating the error now, but it just leaves an empty stream, no operations at all received.  If you reload the browser a few times, you can get one working.  So, the error goes away, but no stream is coming in at all then.  Must be caused by something upstream of this null, to kill the operations.  I don't know.

**Comment by adcpm** [comment]
I can't reproduce this issue the stream is working fine for me when i test stream.html file. Are you using a different file? Can you tell me how you test it?

**Comment by unipsycho** [comment]
OK, I simply load examples/stream.html for my testing.  This all started as my integration with steem.js stopped working on my dev system for the autostream project about a week ago.  Let me do a few tests on another computer here, and try another ISP, as I wonder if something is happening locally here, since you can't reproduce it.  I'll post back here what I find as as I test that.  Thanks so much for helping with this, hope to solve it soon!

**Comment by unipsycho** [comment]
Well, I did lots of work testing this on multiple computers, ISPs, cell phones etc, with and without firewalls and the problem had persisted for 2 more days.  Today, however, it has worked flawless on those some browsers/computers so things are working again as expected.  Little worrisome having no idea what this was, only thing I can think of, is if it is latency based.  My internet connected is pretty bad some evenings and perhaps that was related, but I just don't know, or timeouts/latencies with the blockchain websockets?   Anyway I'll report back if this starts happening again.  I had another user tell me it was occuring for them as well using my autosteem product, but everything seems to be good again now.  Cheers.

**Comment by adcpm** [comment]
The first issue should be fixed. There was another issue using the page stream.html on Firefox because of the document.write method i've removed it and its working fine. If you or an user have another issue please give more details how to test/reproduce it or the error message.
